//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABM11Entities : DbContext
    {
        public ABM11Entities()
            : base("name=ABM11Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<ClientesDirecciones> ClientesDirecciones { get; set; }
        public virtual DbSet<ClientesFuentesContacto> ClientesFuentesContacto { get; set; }
        public virtual DbSet<ClientesTelefonos> ClientesTelefonos { get; set; }
        public virtual DbSet<FuentesContacto> FuentesContacto { get; set; }
        public virtual DbSet<Llamados> Llamados { get; set; }
        public virtual DbSet<LlamadosDestinatarios> LlamadosDestinatarios { get; set; }
        public virtual DbSet<LlamadosMotivosLlamados> LlamadosMotivosLlamados { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<MotivosLlamado> MotivosLlamado { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Rubros> Rubros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
