//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDADES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesTelefonos
    {
        public string Telefono { get; set; }
        public short ClienteId { get; set; }
        public Nullable<int> CiudadId { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
